Repository abhisek247767/AI-ML-DL-Hacktoberfest2024-WB, pull requests merged in 2023-10, with the labels that each got.

#13 Support Vector Machine (SVM)
  Support Vector Machine (SVM)
Labels: documentation, Hacktoberfest, Hacktoberfest-2023

#19 Multivariate Regression Notebook - Hacktoberfest 2023
  EPL-Player-Market-Value-Prediction/README.md
  EPL-Player-Market-Value-Prediction/dataset/epldata_final.csv
  EPL-Player-Market-Value-Prediction/multivariate-regression.ipynb
  EPL-Player-Market-Value-Prediction/requirements.txt
Labels: Hacktoberfest-2023, Hacktoberfest-Accepted

#21 Classification Code - Hacktoberfest2023
  Mobile-Price-Classification/README.md
  Mobile-Price-Classification/dataset/test.csv
  Mobile-Price-Classification/dataset/train.csv
  Mobile-Price-Classification/mobile-price-classification.ipynb
  Mobile-Price-Classification/requirements.txt
Labels: Hacktoberfest, Hacktoberfest-2023, Hacktoberfest-Accepted

#20 Added heart disease prediction model
  heart_disease_prediction_model/cleveland.csv
  heart_disease_prediction_model/framingham.csv
  heart_disease_prediction_model/heart.ipynb
Labels: Hacktoberfest, Hacktoberfest-2023, Hacktoberfest-Accepted

#23 Create Random_forest.txt
  Random_forest.txt
Labels: documentation, Hacktoberfest
