Repository abhisek247767/AI-ML-DL-Hacktoberfest2024-WB, pull requests merged in 2024-10, with the labels that each got.

#47 Hand Controlled Screenshot Opencv
  Hand Controlled Screenshot/handtracking.py
  Hand Controlled Screenshot/handtrackingmodule.py
  Hand Controlled Screenshot/screenshotgesture.py
  Readme.md
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024, review

#49 Made CNN and RNN Explanation and Implementation
  .gitignore
  Neural Networks/CNN.ipynb
  Neural Networks/CNN.md
  Neural Networks/Neural_Nets.md
  Neural Networks/RNN.ipynb
  Neural Networks/RNN.md
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#52 added credit-card-fraud-detection
  credit-card-fraud-detection/credit_card_fraud_detection (2).ipynb
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#45 Added Diabetes-Prediction-Model-eda-svm
  Diabetes-Prediction-Model-eda-svm/diabetes_prediction_dataset.csv
  Diabetes-Prediction-Model-eda-svm/diabeties-prediction-eda-svm.ipynb
  Diabetes-Prediction-Model-eda-svm/model.tflite
  Diabetes-Prediction-Model-eda-svm/tflite model gudie.txt
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024, review

#48 first frontend commit
  frontend/images/ai-img.svg
  frontend/images/ds-img.svg
  frontend/images/ml-img.svg
  frontend/images/model-img-1.jpg
  frontend/images/model-img-2.jpg
  frontend/images/model-img-3.jpg
  frontend/index.html
  frontend/styles.css
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#60 Face Emotion Classification Using FER Dataset
  Face Emotion Classification Using FER Dataset/Face Emotion Classification.ipynb
  Readme.md
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#63 Added a Car Price Predictor with a Next.js frontend
  Car Price Predictor/car-predictor/.eslintrc.json
  Car Price Predictor/car-predictor/.gitignore
  Car Price Predictor/car-predictor/README.md
  Car Price Predictor/car-predictor/next.config.mjs
  Car Price Predictor/car-predictor/package-lock.json
  Car Price Predictor/car-predictor/package.json
  Car Price Predictor/car-predictor/postcss.config.mjs
  Car Price Predictor/car-predictor/public/next.svg
  Car Price Predictor/car-predictor/public/vercel.svg
  Car Price Predictor/car-predictor/src/app/favicon.ico
  Car Price Predictor/car-predictor/src/app/globals.css
  Car Price Predictor/car-predictor/src/app/layout.tsx
  Car Price Predictor/car-predictor/src/app/page.tsx
  Car Price Predictor/car-predictor/src/components/magicui/canvas.tsx
  Car Price Predictor/car-predictor/src/components/magicui/flicker.tsx
  Car Price Predictor/car-predictor/src/components/ui/cover.tsx
  Car Price Predictor/car-predictor/src/components/ui/sparkles.tsx
  Car Price Predictor/car-predictor/src/lib/utils.ts
  Car Price Predictor/car-predictor/tailwind.config.ts
  Car Price Predictor/car-predictor/tsconfig.json
  Car Price Predictor/data.csv
  Car Price Predictor/main.py
  Car Price Predictor/model/LinearRegressionModel.pkl
  Car Price Predictor/model/app.py
  Car Price Predictor/model/cleaned_data.csv
  Car Price Predictor/model/requirements.txt
  logistic_regression_scratch.py
Labels: good first issue, Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#65 Implemented Optimized File Transfer Using Checksums
  Optimized File Transfer Using Checksums.py
  destination_folder/4_mux.mpf.txt
  destination_folder/mux4_1.v.txt
  source_folder/4_mux.mpf.txt
  source_folder/mux4_1.v.txt
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#68 Update README.md
  README.md
Labels: Hacktoberfest

#71 Fixed isue #29 added more explantion with diagram for easy understanding
  kmeans Algorithm/explanation with diagram.docx
  kmeans Algorithm/kmeans.png
  kmeans Algorithm/kmeans_readme.md
Labels: good first issue, Hacktoberfest, Hacktoberfest 2024

#78 A brief explanation about transfer Learning and its implementaion using vgg16.
  Fruits-classifier-using-transfer-learning/Fruits_classifier.py
  Fruits-classifier-using-transfer-learning/Transfer_learning.docx
Labels: good first issue, Hacktoberfest, Hacktoberfest 2024

#81 Create randomForestAlgo.py
  randomForestAlgo.py
Labels: good first issue, Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#84 Added Health Recommender System.
  Ai_Health_Recommender/.gitignore
  Ai_Health_Recommender/datasets/Symptom-severity.csv
  Ai_Health_Recommender/datasets/Training.csv
  Ai_Health_Recommender/datasets/description.csv
  Ai_Health_Recommender/datasets/diets.csv
  Ai_Health_Recommender/datasets/medications.csv
  Ai_Health_Recommender/datasets/precautions_df.csv
  Ai_Health_Recommender/datasets/symptoms_df.csv
  Ai_Health_Recommender/datasets/workout_df.csv
  Ai_Health_Recommender/main.py
  Ai_Health_Recommender/models/svc.pkl
  Ai_Health_Recommender/requirements.txt
  Ai_Health_Recommender/static/img.png
  Ai_Health_Recommender/templates/about.html
  Ai_Health_Recommender/templates/blog.html
  Ai_Health_Recommender/templates/contact.html
  Ai_Health_Recommender/templates/developer.html
  Ai_Health_Recommender/templates/index.html
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#90 Added Number plate recognition using OpenCV and EasyOC
  Automatic Number Plate Recognition/image1.jpg
  Automatic Number Plate Recognition/image2.jpg
  Automatic Number Plate Recognition/image3.jpg
  Automatic Number Plate Recognition/image4.jpg
  Automatic Number Plate Recognition/main.ipynb
Labels: good first issue, Hacktoberfest, Hacktoberfest 2024

#91 Wine Quality Prediction and Twitter Sentiment Analysis
  Twitter Senti Analysis/Sentiment_Analysis.ipynb
  Twitter Senti Analysis/Twitter Sentiments.csv
  Wine Quality Prediction/Wine_Quality_Prediction.ipynb
  Wine Quality Prediction/trained_model.sav
  Wine Quality Prediction/winequality-red.csv
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#93 Added Credit card fraud detection model
  Credit card fraud detection model using K-means clustering Working.ipynb
  Credit card fraud detection model using K-means clustering.html
Labels: good first issue, Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#98 Feature/sentiment analysis
  Sentiment_Analysis_using LSTM/model.ipynb
Labels: Hacktoberfest, Hacktoberfest 2024

#99 House Price Prediction
  House-Price-Prediction-Using-Machine-Learning/Readme.md
  House-Price-Prediction-Using-Machine-Learning/data/House_Data.csv
  House-Price-Prediction-Using-Machine-Learning/main file/main.ipynb
Labels: good first issue, Hacktoberfest, Hacktoberfest 2024

#112 feat: Add implementation of Adaptive Neural Complexity (ANC) algorithm
  .DS_Store
  ANC-Algo/README.md
  ANC-Algo/adaptive_neural_complexity.py
  Readme.md
Labels: good first issue, Hacktoberfest, Hacktoberfest 2024

#118 Add files via upload
  Datacamp-data-science-associate-certification-HACKTOBERFEST/README.md
  Datacamp-data-science-associate-certification-HACKTOBERFEST/bike image.jpeg
  Datacamp-data-science-associate-certification-HACKTOBERFEST/electric_bike_ratings_2212.csv
  Datacamp-data-science-associate-certification-HACKTOBERFEST/notebook.ipynb
Labels: Hacktoberfest

#125 Update logistic_regression_scratch.py
  logistic_regression_scratch.py
Labels: good first issue, Hacktoberfest, Hacktoberfest 2024

#127 Helmet Detection Using Faster R-CNN with ResNet50 backbone
  Helmet_Detection/Helmet_Detection.ipynb
  Helmet_Detection/readme.md
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#128 add image-to-text model
  image-to-text model/model.py
  image-to-text model/model_implementation.txt
  image-to-text model/model_readme.md
  image-to-text model/requirements.txt
  image-to-text model/result.png
Labels: Hacktoberfest, Hacktoberfest-Accepted, Hacktoberfest 2024

#40 Fixed issue #29 Kmeans Algorithm
  kmeans_readme.md
Labels: good first issue, Hacktoberfest, feedback, review
